const CONFIG = {
  GIANNI_LOGO_IMG: '/Logo.webp',
  GIANNI_NAV_MAIN_SITE: true,
  GIANNI_BLOG_NAV_PILLS: true,
  GIANNI_POST_COVER_ENABLE: false,
  GIANNI_READING_PROGRESS: true,
  GIANNI_HERO_ENABLE: false,
  GIANNI_ANIMATE_LISTS: true,
  GIANNI_MOBILE_NAV_DRAWER: true,
  GIANNI_ARTICLE_RECOMMEND_POSTS: true,
  GIANNI_SIDEBAR_PROFILE: true,
  GIANNI_SIDEBAR_CATEGORIES: true,
  GIANNI_SIDEBAR_TAGS: true,
  GIANNI_SIDEBAR_ANNOUNCEMENT: true,

  GIANNI_MENU_CATEGORY: true,
  GIANNI_MENU_TAG: true,
  GIANNI_MENU_ARCHIVE: true,
  GIANNI_MENU_SEARCH: true
}
export default CONFIG
