const CONFIG = {
  GIANNI_AVATAR_IMG: '/avatar.webp',
  GIANNI_POST_COVER_ENABLE: false,
  GIANNI_ANIMATE_LISTS: true,
  GIANNI_ARTICLE_RECOMMEND_POSTS: true,

  GIANNI_MENU_CATEGORY: true,
  GIANNI_MENU_TAG: true,
  GIANNI_MENU_ARCHIVE: true,
  GIANNI_MENU_SEARCH: true,

  // Phase 1: Mobile responsive
  GIANNI_MOBILE_BLOG_PILLS: true,
  GIANNI_MOBILE_TOC_DRAWER: true,
  GIANNI_MOBILE_SIDEBAR_DRAWER: true,

  // Phase 2: Missing components
  GIANNI_ARTICLE_COPYRIGHT: true,
  GIANNI_ARTICLE_JUMP_TO_COMMENT: true,

  // Ads
  GIANNI_POST_AD_ENABLE: false
}
export default CONFIG
